stages:
  - test
  - deploy

before_script:
  # Install git.
  - apt-get update -qq && apt-get install -y git
  - apt-get install -y glpk-utils # the glpsol executable is needed for the solver glpk
  - apt-get install -y g++ # the g++ compiler is needed for compiling C++ programs
  - apt-get install wget curl -y # to donwload miniconda
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda # run the installer
  - export PATH="$HOME/miniconda/bin:$PATH" # add the miniconda path to the PATH

  # Create a conda environment and install poetry such that test/python_module can be installed.
  - eval "$(conda shell.bash hook)"
  - conda create --name testenv python=3.10 -y
  - conda activate testenv
  - conda install -c conda-forge poetry -y
  - pip install --upgrade pip setuptools wheel
  - pip uninstall -y distlib && pip install --no-cache-dir --force-reinstall distlib
  - cd test/python_module
  - poetry install
  - cd ../..
  - git clone https://gitlab.sintef.no/harald.svendsen/timeseries.git
  - cd timeseries
  - poetry install
  - cd ..
  - git clone https://github.com/iDesignRES/Tecnalia.git
  - cd Tecnalia/examples/pv_power_plants
  - poetry install
  - cd ../../..
  
  # Add the public General registry.
  - julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General"))'
  
  # Build the PyCall package.
  - julia --project=. -e 'using Pkg; Pkg.add("PyCall");
    ENV["PYTHON"] = joinpath("/root/miniconda/envs", "testenv", "bin", "python");
    Pkg.build("PyCall");'

# Below is the template to run the tests in Julia
.test_template: &test_definition
  stage: test
  script:
    - echo "Run tests"
    - julia -e 'using Pkg; Pkg.Registry.status()'

    # Run the tests.
    - julia --project=. -e 'using Pkg; Pkg.test(; coverage = true);
        Pkg.add("Coverage");
        Pkg.instantiate();
        using Coverage;
        processed = process_folder();
        covered_lines, total_lines = get_summary(processed);
        percentage = covered_lines / total_lines * 100;
        return println("Code coverage $(percentage)%")'
  coverage: "/\\(\\d+.\\d+\\%\\) covered/"
  rules:
    - when: always


test:1.10:
  image: julia:1.10
  <<: *test_definition


# Test that the pages compile, without making it public. Only runs on merge requests.
test:pages:
  image: julia:1.10
  stage: test
  script:
    - julia --project=docs -e 'import Pkg; Pkg.develop(;path=".");Pkg.instantiate()' # Initialize environment
    - julia --project=docs docs/make.jl                       # Build documentation
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Deploy the documentation.
pages:
  stage: deploy
  image: julia:latest
  script:
    - julia --project=docs -e 'import Pkg; Pkg.develop(;path=".");Pkg.instantiate()' # Initialize environment
    - julia --project=docs docs/make.jl                       # Build documentation
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  rules:
    # Only execute this on the default branch and on merge requests.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH