name: before-script
description: "Common before script"
runs:
  using: "composite"
  steps:
    - name: Update and install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git glpk-utils g++ cmake wget curl python3-pip
        pip install conan
        conan profile detect
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash

        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda create --name testenv python=3.11 -y
        conda activate testenv
        conda install -c conda-forge poetry -y

        cd "$GITHUB_WORKSPACE/test/python_module"
        poetry install
        cd "$GITHUB_WORKSPACE"

        cd "$GITHUB_WORKSPACE/submodules/wind_power_timeseries"
        poetry install
        cd "$GITHUB_WORKSPACE"

        cd "$GITHUB_WORKSPACE/submodules/Tecnalia_Solar-Energy-Model"
        poetry install
        cd "$GITHUB_WORKSPACE/submodules/Tecnalia_Building-Stock-Energy-Model"
        poetry install
        cd "$GITHUB_WORKSPACE"

        cd "$GITHUB_WORKSPACE/submodules/CHP_modelling"
        mkdir build
        cd build
        conan install .. --output-folder=. --build=missing -s compiler.cppstd=17 -s arch=x86_64
        cmake .. -DCMAKE_TOOLCHAIN_FILE="${PWD}/conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cd "$GITHUB_WORKSPACE"
      shell: bash
