name: before-script
description: "Common before script"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (apt)
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git glpk-utils g++ cmake wget curl

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash

    - name: Setup Conda Environment and Install Poetry
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda create --name testenv python=3.10 -y
        conda activate testenv
        conda install -c conda-forge poetry -y

        echo "MAIN_DIR=$(pwd)" >> $GITHUB_ENV
        cd test/python_module
        poetry install
        cd "$MAIN_DIR"

        git clone https://gitlab.sintef.no/harald.svendsen/timeseries.git
        cd timeseries
        poetry install
        cd "$MAIN_DIR"

        git clone https://github.com/iDesignRES/Tecnalia.git
        cd Tecnalia/examples/pv_power_plants
        poetry install
        cd ../building_energy_process
        poetry install
        cd "$MAIN_DIR"

        git clone https://github.com/iDesignRES/CHP_modelling.git
        cd CHP_modelling
        git checkout feat/newtestsetup
        mkdir build
        cd build
        cmake ..
        make
        cd "$MAIN_DIR"

    - name: Add Julia General Registry and build PyCall
      run: |
        julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General"))'

        julia --project=. -e '
          using Pkg;
          Pkg.add("PyCall");
          ENV["PYTHON"] = joinpath(ENV["HOME"], "miniconda", "envs", "testenv", "bin", "python");
          Pkg.build("PyCall");
        '