name: CI
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- version: '1'  # The latest point-release (Linux)
          #  os: ubuntu-latest
          #  arch: x64
          - version: 'lts'  # The long term stable version (Linux) 
            os: ubuntu-latest
            arch: x64
          #- version: '1'
          #  os: windows-latest
          #  arch: x64
          - version: 'lts'
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Recommended: ensure MSVC environment for conan/cmake on Windows
      - name: Setup MSVC Dev Cmd
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - uses: ./.github/actions/before-script
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run Julia tests inside the testenv-enviornment in Miniconda (Linux)
        if: runner.os == 'Linux'
        run: |
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda activate testenv
          julia --project=. -e '
            using Pkg;
            ENV["PYTHON"] = joinpath(ENV["HOME"], "miniconda", "envs", "testenv", "bin", "python");
            Pkg.build("PyCall");
            Pkg.test(; coverage=true)
          '
        shell: bash
      - name: Run Julia tests inside the testenv-environment in Miniconda (Windows)
        if: runner.os == 'Windows'
        run: |
          $conda = Join-Path $env:USERPROFILE "miniconda\Scripts\conda.exe"
          & $conda "shell.powershell" "hook" | Out-String | Invoke-Expression
          conda activate testenv
          $env:PATH = "$env:CONDA_PREFIX;$env:CONDA_PREFIX\Scripts;$env:PATH"

          julia --project=. -e 'using Pkg; ENV["PYTHON"] = joinpath(ENV["USERPROFILE"], "miniconda", "envs", "testenv", "python.exe"); Pkg.build("PyCall"); Pkg.test(; coverage=true)'
        shell: pwsh
