name: Documentation
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        shell: julia --color=yes --project=docs/ {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: |
<<<<<<< HEAD
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash
          conda activate testenv
=======
          sudo apt-get update -qq
          sudo apt-get install -y git glpk-utils g++ cmake wget curl
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda init bash

          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda create --name testenv python=3.10 -y
          conda activate testenv
          conda install -c conda-forge poetry -y

          cd "$GITHUB_WORKSPACE/test/python_module"
          poetry install
<<<<<<< HEAD
          cd "$MAIN_DIR"
>>>>>>> fc487c5 (Check if the issue is with relative pathing and fix documentation)
=======
          cd "$GITHUB_WORKSPACE"
>>>>>>> 836dcdc (Fix relative bash pathings also for documentation.yml)

          julia --color=yes --project=docs/ docs/make.jl '
            using Pkg;
            ENV["PYTHON"] = joinpath(ENV["HOME"], "miniconda", "envs", "testenv", "bin", "python");
            Pkg.build("PyCall");
            Pkg.test(; coverage=true)
          '